name: Terraform Plan

on:
  push:
    branches-ignore:
      - main  # Ignores pushes to the main branch

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::590183835826:role/github-actions
          aws-region: us-east-1  # Update this to your region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Format Terraform Files
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan
